baseURL = 'https://metapatterns.io/'
languageCode = 'en-us'
title = 'Architectural Metapatterns'
theme = 'hugo-book'
BookComments = false

enableRobotsTXT = true
printPathWarnings = true
disableKinds = ['taxonomy', 'term']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2

[params]
  BookToC = true
  BookSection = '/'
  BookTheme = 'auto'
  description = "The Metapatterns website is a compendium and classification of architectural patterns based on the assumption that structure determines function."
  images = ["/favicon.svg"]

[sitemap]
  changeFreq = 'weekly'

[author]
  name = "Denys Poltorak"
  location = "Ukraine"

[imaging]
  anchor = "Center"
  hint = "drawing"
  quality = 100
  
[server]
  [server.headers]
    for = '/**.svgz'
    [server.headers.values]
      Content-Encoding = 'gzip'
      Vary = 'Accept-Encoding'

[mediaTypes."image/svg+xml"]
  suffixes = ["svg","svgz"]
