baseURL = 'https://metapatterns.io/'
languageCode = 'en-us'
title = 'Architectural Metapatterns'
theme = 'hugo-book'
BookComments = false

enableRobotsTXT = true
printPathWarnings = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2

[params]
  BookToC = true
  BookSection = '/'
  BookTheme = 'auto'
  description = "The Metapatterns website is a compendium and classification of architectural patterns based on the assumption that structure determines function."
  images = ["/Cover.png"]

[author]
  name = "Denys Poltorak"
  location = "Ukraine"

[imaging]
  anchor = "Center"
  hint = "drawing"
  quality = 100
