baseURL = 'https://metapatterns.io/'
languageCode = 'en-us'
title = 'Architectural Metapatterns'
theme = 'hugo-book'
BookComments = false

enableRobotsTXT = true
printPathWarnings = true
disableKinds = ['taxonomy', 'term', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2

[params]
  BookToC = true
  BookSection = '/'
  BookTheme = 'auto'
  BookLogo = 'favicon.svg'
  description = "Explore how patterns are interrelated and work together."
  images = ["/web-app-manifest-512x512.png"]
  author = "Denys Poltorak"

[sitemap]
  changeFreq = 'weekly'

[imaging]
  anchor = "Center"
  hint = "drawing"
  quality = 100
  
[server]
  [server.headers]
    for = '/**.svgz'
    [server.headers.values]
      Content-Encoding = 'gzip'
      Vary = 'Accept-Encoding'

[mediaTypes."image/svg+xml"]
  suffixes = ["svg","svgz"]
